### PR TITLE
bump download links to 0.1.9

### PR DESCRIPTION
**Pull request by karamble**

### CODE REVIEW

**Review by jholdstock — CHANGES_REQUESTED** [review]
Some of these links dont work because filenames have changed. Posted a question in web ops matrix channel.

**Comment by jholdstock** [comment]
Do you fancy opening a dcrweb PR as well to add 0.1.9 to software releases?

**Comment by karamble** [comment]
squashed the V prefix into the download links.
Download links are working now, the only file missing is BR GUI for windows:
[bisonrelay-windows-amd64-v0.1.9.msix](https://github.com/companyzero/bisonrelay/releases/download/v0.1.9/bisonrelay-windows-amd64-v0.1.9.msix)
After BRUIG for Windows is released, this PR can go in and the live server updated

**Comment by xaur** [comment]
@karamble iirc the MSIX installer has been discontinued. Has it been reverted?

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
